User:
  user-1:
    client_name: Link
    ip_address: 192.168.0.1
    register_status: true
    socket_number: 8888
    subject_interest:
    - ps5
    - spiderman
  user-2:
    client_name: Jack
    ip_address: 192.168.0.2
    register_status: true
    socket_number: 1234
    subject_interest: game
  user-3:
    client_name: User1
    ip_address: local_host
    register_status: true
    socket_number: 8888
    subject_interest: game
  user-4:
    client_name: Haocheng
    ip_address: 192.168.0.3
    register_status: true
    socket_number: 8888
    subject_interest: game
