User:
  user 1:
    Client_Name: Jack
    IP_address: localhost
    Register_Status: true
    Socket_Number: 8888
    Subject_of_Interest: []
  user 2:
    Client_Name: John
    IP_address: localhost
    Register_Status: true
    Socket_Number: 2222
    Subject_of_Interest: []
  user 3:
    Client_Name: Josh
    IP_address: localhost
    Register_Status: true
    Socket_Number: 3333
    Subject_of_Interest: []
  user 4:
    Client_Name: Test
    IP_address: localhost
    Register_Status: true
    Socket_Number: 1111
    Subject_of_Interest: []
  user 5:
    Client_Name: Lina
    IP_address: loalhost
    Register_Status: true
    Socket_Number: 1111
    Subject_of_Interest: []
  user 6:
    Client_Name: Jason
    IP_address: localhost
    Register_Status: true
    Socket_Number: 1111
    Subject_of_Interest: []
