User:
  -1679514339:
    client_name: List
    ip_address: local_host
    register_status: true
    socket_number: 8888
    subject_interest:
    - ps5
    - spiderman
    - list
  922635503:
    client_name: Philippe
    ip_address: local_host
    register_status: true
    socket_number: 8888
    subject_interest: game
  1303647551:
    client_name: Jack
    ip_address: local_host
    register_status: true
    socket_number: 8888
    subject_interest: game
