User:
  user-1:
    client_name: Link
    ip_address: localhost
    register_status: true
    socket_number: SO
    subject_interest:
    - ps5
    - spiderman
  user-2:
    client_name: Jack
    ip_address: local_host
    register_status: true
    socket_number: 8888
    subject_interest: game
  user-3:
    client_name: Jack
    ip_address: local_host
    register_status: true
    socket_number: 8888
    subject_interest: game
  user-4:
    client_name: Haocheng
    ip_address: local_host
    register_status: true
    socket_number: 8888
    subject_interest: game
