SOI:
  nintendo:
  - default
  pc:
  - default
  - new pc
  - new pc 1
  - new pc 11
  - new pc 4
  - wow pc
  ps:
  - Text1
  - Text2
  - Text3
  vr:
  - Text1
  - Text2
  - Text3
  xbox:
  - default
User:
  -1087307508706077920:
    client_name: JACK
    ip_address: 127.0.0.11
    register_status: false
    socket_number: 8888
    subject_interest:
    - pc
  -1842467073:
    client_name: PHIL
    ip_address: 127.0.0.12
    register_status: false
    socket_number: 8888
    subject_interest: ''
  863709596:
    client_name: HAOCHENG
    ip_address: 127.0.0.10
    register_status: false
    socket_number: 8888
    subject_interest:
    - pc
